# Generated by Django 4.2.5 on 2023-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebox',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
    ]
